#!/usr/bin/env python3
"""
BrainWavesEmulator.py is a stand-in for the real EEG headset, for testing
the maze game without wearing the BCI cap. Please be aware: you need the small
black screen generated by this script to be visible for the emulator to work.

Sends the same kind of LSL messages BrainWavesVisualizer.py would send from
real brain signals, but triggered by arrow key presses instead. Run this
alongside Main.py (see README.md) to play the maze with a keyboard.

Controls:
  Esc / Q : quit

Deps: pygame, pylsl

NOTE: DO NOT CHANGE THIS FILE
"""

import argparse
import time

import pygame
from pylsl import StreamInfo, StreamOutlet, cf_float32

from Config import freq1, freq2, freq3, freq4

# Which frequency each arrow key sends. These values come straight from
# Config.py, so if you change an arrow's frequency there (Config.DIRECTIONS),
# this mapping updates automatically — no need to edit this file.
FREQS = {
    pygame.K_UP:    freq2,  # North
    pygame.K_LEFT:  freq3,  # West
    pygame.K_DOWN:  freq1,  # South
    pygame.K_RIGHT: freq4,  # East
}

# --- DO NOT CHANGE ---
def make_outlet(name: str, stype: str, source_id: str) -> StreamOutlet:
    """Create and return an LSL outlet that publishes single float samples (Hz)."""
    info = StreamInfo(
        name=name,
        type=stype,
        channel_count=1,
        nominal_srate=0,          # irregular/event-like
        channel_format=cf_float32,
        source_id=source_id,
    )
    return StreamOutlet(info)

# --- DO NOT CHANGE ---
def main():
    ap = argparse.ArgumentParser(description="Send LSL frequencies from arrow key presses.")
    ap.add_argument("--name", type=str, default="BCI_FREQ", help="LSL stream name (default: BCI_FREQ)")
    ap.add_argument("--type", type=str, default="BCI", help="LSL stream type (default: BCI)")
    ap.add_argument("--repeat", type=float, default=0.0,
                    help="If >0, continuously resend while key is held at this rate (Hz). Default: 0 (send once per keydown).")
    args = ap.parse_args()

    outlet = make_outlet(args.name, args.type, source_id="arrow_keys_freq_emulator")

    pygame.init()
    pygame.display.set_caption("Arrow → LSL (freq emitter)")
    # Small unobtrusive window just to capture focus/events
    screen = pygame.display.set_mode((420, 140))
    font = pygame.font.SysFont("Consolas,Menlo,Monaco,DejaVu Sans Mono", 16)

    last_sent_label = "—"
    held = {}  # key -> next_send_time (for repeat mode)
    clock = pygame.time.Clock()

    print(f"[lsl] Outlet up: name='{args.name}', type='{args.type}', ch=1, srate=0, fmt=float32")
    print("[info] Press arrow keys to send frequencies. (Esc/Q to quit)")

    running = True
    while running:
        now = time.time()

        # Handle events
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False

            elif event.type == pygame.KEYDOWN:
                if event.key in (pygame.K_ESCAPE, pygame.K_q):
                    running = False
                    continue

                if event.key in FREQS:
                    f = float(FREQS[event.key])
                    outlet.push_sample([f])
                    last_sent_label = f"{f:.4f} Hz"
                    print(f"[lsl] sent {f:.4f} Hz")

                    if args.repeat > 0:
                        period = 1.0 / args.repeat
                        held[event.key] = now + period

            elif event.type == pygame.KEYUP:
                # Stop repeating when key released
                if event.key in held:
                    del held[event.key]

        # Repeat mode: resend while key is held
        if args.repeat > 0 and held:
            period = 1.0 / args.repeat
            for k in list(held.keys()):
                if pygame.key.get_pressed()[k]:
                    if now >= held[k]:
                        f = float(FREQS[k])
                        outlet.push_sample([f])
                        last_sent_label = f"{f:.4f} Hz"
                        print(f"[lsl] sent {f:.4f} Hz (repeat)")
                        held[k] = now + period
                else:
                    del held[k]

        # Minimal UI
        screen.fill((16, 16, 16))
        lines = [
            "Arrow → LSL frequency emitter",
            f"Up: {freq2:.1f} Hz   Down: {freq1:.1f} Hz   Left: {freq3:.1f} Hz   Right: {freq4:.1f} Hz",
            f"Last sent: {last_sent_label}",
            "Esc/Q to quit",
        ]
        y = 16
        for s in lines:
            surf = font.render(s, True, (220, 220, 220))
            screen.blit(surf, (16, y))
            y += 26

        pygame.display.flip()
        clock.tick(120)

    pygame.quit()

if __name__ == "__main__":
    main()